hide circle

skinparam shadowing false

skinparam defaultFontSize 12
skinparam defaultFontName Monaco

skinparam class {
  BackgroundColor #eeeeee
  ArrowColor #656b49
  BorderColor #333333
}

skinparam state {
  StartColor #445588
  EndColor #D01040
  BackgroundColor #eeeeee
  BorderColor #333333
}
